[build]
builder = "RAILPACK"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"
buildEnvironment = "V3"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm start"
sleepApplication = false
useLegacyStacker = false
ipv6EgressEnabled = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10